/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package io.github.ramanji025


import spock.lang.Specification

/**
 * A simple unit test for the 'io.github.ramanji025.greeting' plugin.
 */
class GradleLiquibasePluginTest extends Specification {
   /* def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("io.github.ramanji025.greeting")

        then:
        project.tasks.findByName("greeting") != null
    }*/
}
